### ISSUE TITLE
Missing namespace in package?

### ISSUE THREAD

**Issue by Rakesh6720** [microsoft/MRLightingTools-Unity#2]
Assets\MixedRealityToolkit.LightingTools\Examples\Scripts\LightPreviewController.cs(191,9): error CS0234: The type or namespace name 'Raycast' does not exist in the namespace 'Microsoft.MixedReality.Toolkit.Physics' (are you missing an assembly reference?)

Opened Unity 2018.3.  Installed Windows 10 SDK 18136.  Changed build settings to UWP with mixed reality as VR dev kit in XR settings.  Imported MRTK package foundation.  Nothing broken.

Imported Lighting Tool Kit.  Received the error.

**Comment by flycanflyxd** [comment]
Modify 'Physics.Raycast' to 'UnityEngine.Physics.Raycast'.

**Comment by maluoi** [comment]
Should be resolved as of v0.1.2
